### ISSUE TITLE
㕼(U+357C)字形錯誤

### ISSUE THREAD

**Issue by Des-Magmeta** [Steve-Yuu/YshiShuti#1]
該字結構應為「⿰口⿹勹⿺𠃊乂」而非「⿰口匈」，請參考 [Plan Kai](https://github.com/Des-Magmeta/PlanKai) 製作字形。![Screenshot_20231002_152150.jpg](https://github.com/Steve-Yuu/YshiShuti/assets/125174106/50d54b75-a246-4808-a727-8a36010a676b)

**Comment by Steve-Yuu** [comment]
收到，本人修正字形时候当时未能跟进计划楷更新，未在意部分计划楷原本错误的汉字，为此给您带来不便，抱歉，同时感谢提醒，目前本人已经跟进修复
<img width="32" alt="image" src="https://github.com/Steve-Yuu/YshiShuti/assets/108906358/e879993e-dd4a-4a52-b4c3-79408b54a4d2">


> 該字結構應為「⿰口⿹勹⿺𠃊乂」而非「⿰口匈」，請參考 [Plan Kai](https://github.com/Des-Magmeta/PlanKai) 製作字形。![Screenshot_20231002_152150.jpg](https://user-images.githubusercontent.com/125174106/271906578-50d54b75-a246-4808-a727-8a36010a676b.jpg)
